import React, { createContext, useState, useEffect, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    brandName: "AI ElderCare Guardian",
    subtitle: "Voice-Based Care Assistant For Elderly People",
    getStarted: "Get Started",
    learnMore: "Learn More",
    features: "Features",
    howItWorks: "How It Works",
    testimonials: "Testimonials",
    dashboard: "Dashboard",
    profiles: "Elderly Profiles",
    medicines: "Medicine Management",
    wellness: "Wellness Check",
    voice: "Voice Interaction",
    emergency: "Emergency Center",
    mood: "Mood Tracking",
    meals: "Meal Monitoring",
    notifications: "Notification Center",
    reports: "Weekly Report",
    admin: "Admin Control",
    settings: "Settings",
    logout: "Logout",
    totalProfiles: "Total Elderly Profiles",
    medicineCompliance: "Medicine Compliance %",
    healthStatus: "Health Status",
    emergencyAlerts: "Emergency Alerts Count",
    moodScore: "Mood Score",
    lastCheckin: "Last Check-in Time",
    emergencyDetected: "Emergency Detected",
    medicineMissed: "Medicine Missed",
    noResponse: "No Response Alert",
    moodConcern: "Mood Concern Flagged",
    healthConcern: "Health Concern Flagged",
    changeLanguage: "Change Language",
    hello: "Hello",
    relationship: "Relationship",
    preferredLang: "Preferred Language",
    address: "Address",
    medConditions: "Medical Conditions",
    bloodGroup: "Blood Group",
    phone: "Phone Number",
    actions: "Actions",
    addProfile: "Add Elderly Profile",
    editProfile: "Edit Elderly Profile",
    save: "Save",
    cancel: "Cancel",
    confirmDelete: "Are you sure you want to delete this profile?",
    complianceReport: "Medicine Compliance Report",
    wellnessTimeline: "Wellness Check-in Timeline",
    moodTrend: "Mood Trends & Analytics",
    mealStatus: "Meal Status Tracker",
    weeklySummary: "Weekly Health Summary"
  },
  te: {
    brandName: "AI ఎల్డర్‌కేర్ గార్డియన్",
    subtitle: "వృద్ధుల కోసం వాయిస్ ఆధారిత సంరక్షణ అసిస్టెంట్",
    getStarted: "ప్రారంభించండి",
    learnMore: "మరింత తెలుసుకోండి",
    features: "ఫీచర్లు",
    howItWorks: "ఇది ఎలా పనిచేస్తుంది",
    testimonials: "అభిప్రాయాలు",
    dashboard: "డాష్‌బోర్డ్",
    profiles: "వృద్ధుల ప్రొఫైల్స్",
    medicines: "మందుల నిర్వహణ",
    wellness: "ఆరోగ్య తనిఖీ",
    voice: "వాయిస్ పరస్పర చర్య",
    emergency: "అత్యవసర కేంద్రం",
    mood: "మూడ్ ట్రాకింగ్",
    meals: "భోజన పర్యవేక్షణ",
    notifications: "నోటిఫికేషన్ సెంటర్",
    reports: "వారపు నివేదిక",
    admin: "అడ్మిన్ నియంత్రణ",
    settings: "సెట్టింగులు",
    logout: "లాగ్ అవుట్",
    totalProfiles: "మొత్తం ప్రొఫైల్‌లు",
    medicineCompliance: "మందుల సమ్మతి %",
    healthStatus: "ఆరోగ్య స్థితి",
    emergencyAlerts: "అత్యవసర హెచ్చరికల కౌంట్",
    moodScore: "మూడ్ స్కోరు",
    lastCheckin: "చివరి చెక్-ఇన్ సమయం",
    emergencyDetected: "అత్యవసర పరిస్థితి గుర్తించబడింది",
    medicineMissed: "మందులు వేసుకోలేదు",
    noResponse: "స్పందన లేని హెచ్చరిక",
    moodConcern: "మూడ్ ఆందోళన గుర్తించబడింది",
    healthConcern: "ఆరోగ్య ఆందోళన గుర్తించబడింది",
    changeLanguage: "భాష మార్చండి",
    hello: "హలో",
    relationship: "సంబంధం",
    preferredLang: "ప్రాధాన్యత కలిగిన భాష",
    address: "చిరునామా",
    medConditions: "వైద్య పరిస్థితులు",
    bloodGroup: "బ్లడ్ గ్రూప్",
    phone: "ఫోన్ నంబర్",
    actions: "చర్యలు",
    addProfile: "ప్రొఫైల్ జోడించు",
    editProfile: "ప్రొఫైల్ సవరించు",
    save: "భద్రపరచు",
    cancel: "రద్దు చేయి",
    confirmDelete: "ఈ ప్రొఫైల్‌ను తొలగించాలనుకుంటున్నారా?",
    complianceReport: "మందుల వాడకం నివేదిక",
    wellnessTimeline: "రోజువారీ ఆరోగ్య కాలక్రమం",
    moodTrend: "మూడ్ ట్రెండ్స్ & విశ్లేషణ",
    mealStatus: "భోజన స్థితి ట్రాకర్",
    weeklySummary: "వారపు ఆరోగ్య సారాంశం"
  },
  hi: {
    brandName: "एआई एल्डरकेयर गार्जियन",
    subtitle: "बुजुर्गों के लिए आवाज-आधारित देखभाल सहायक",
    getStarted: "शुरू करें",
    learnMore: "और जानें",
    features: "विशेषताएं",
    howItWorks: "यह कैसे काम करता है",
    testimonials: "प्रशंसापत्र",
    dashboard: "डैशबोर्ड",
    profiles: "बुजुर्ग प्रोफाइल",
    medicines: "दवा प्रबंधन",
    wellness: "दैनिक स्वास्थ्य जांच",
    voice: "आवाज बातचीत",
    emergency: "आपातकालीन केंद्र",
    mood: "मनोदशा ट्रैकिंग",
    meals: "भोजन निगरानी",
    notifications: "अधिसूचना केंद्र",
    reports: "साप्ताहिक रिपोर्ट",
    admin: "एडमिन पैनल",
    settings: "सेटिंग्स",
    logout: "लॉग आउट",
    totalProfiles: "कुल बुजुर्ग प्रोफाइल",
    medicineCompliance: "दवा अनुपालन %",
    healthStatus: "स्वास्थ्य स्थिति",
    emergencyAlerts: "आपातकालीन अलर्ट संख्या",
    moodScore: "मनोदशा स्कोर",
    lastCheckin: "अंतिम चेक-इन समय",
    emergencyDetected: "आपातकालीन स्थिति का पता चला",
    medicineMissed: "दवा छूट गई",
    noResponse: "कोई प्रतिक्रिया नहीं",
    moodConcern: "मनोदशा की चिंता",
    healthConcern: "स्वास्थ्य संबंधी चिंता",
    changeLanguage: "भाषा बदलें",
    hello: "नमस्ते",
    relationship: "संबंध",
    preferredLang: "पसंदीदा भाषा",
    address: "पता",
    medConditions: "चिकित्सीय स्थितियां",
    bloodGroup: "रक्त समूह",
    phone: "फ़ोन नंबर",
    actions: "कार्रवाई",
    addProfile: "बुजुर्ग प्रोफाइल जोड़ें",
    editProfile: "बुजुर्ग प्रोफाइल संपादित करें",
    save: "सहेजें",
    cancel: "रद्द करें",
    confirmDelete: "क्या आप निश्चित रूप से इस प्रोफ़ाइल को हटाना चाहते हैं?",
    complianceReport: "दवा अनुपालन रिपोर्ट",
    wellnessTimeline: "दैनिक स्वास्थ्य टाइमलाइन",
    moodTrend: "मनोदशा रुझान और विश्लेषण",
    mealStatus: "भोजन स्थिति ट्रैकर",
    weeklySummary: "साप्ताहिक स्वास्थ्य सारांश"
  },
  es: {
    brandName: "AI ElderCare Guardian",
    subtitle: "Asistente de Voz para el Cuidado de Adultos Mayores",
    getStarted: "Empezar",
    learnMore: "Aprender más",
    features: "Características",
    howItWorks: "Cómo Funciona",
    testimonials: "Testimonios",
    dashboard: "Panel de Control",
    profiles: "Perfiles de Ancianos",
    medicines: "Control de Medicinas",
    wellness: "Control de Bienestar",
    voice: "Interacción de Voz",
    emergency: "Centro de Emergencias",
    mood: "Control de Estado de Ánimo",
    meals: "Monitoreo de Comidas",
    notifications: "Centro de Notificaciones",
    reports: "Reporte Semanal",
    admin: "Control de Admin",
    settings: "Ajustes",
    logout: "Cerrar Sesión",
    totalProfiles: "Perfiles Totales",
    medicineCompliance: "Cumplimiento de Medicinas %",
    healthStatus: "Estado de Salud",
    emergencyAlerts: "Alertas de Emergencia",
    moodScore: "Índice de Ánimo",
    lastCheckin: "Último Registro",
    emergencyDetected: "Emergencia Detectada",
    medicineMissed: "Medicina Omitida",
    noResponse: "Sin Respuesta",
    moodConcern: "Preocupación de Ánimo",
    healthConcern: "Preocupación de Salud",
    changeLanguage: "Cambiar Idioma",
    hello: "Hola",
    relationship: "Relación",
    preferredLang: "Idioma Preferido",
    address: "Dirección",
    medConditions: "Condiciones Médicas",
    bloodGroup: "Grupo Sanguíneo",
    phone: "Teléfono",
    actions: "Acciones",
    addProfile: "Agregar Perfil",
    editProfile: "Editar Perfil",
    save: "Guardar",
    cancel: "Cancelar",
    confirmDelete: "¿Está seguro de que desea eliminar este perfil?",
    complianceReport: "Reporte de Cumplimiento",
    wellnessTimeline: "Cronología de Bienestar",
    moodTrend: "Tendencias de Ánimo",
    mealStatus: "Estado de Comidas",
    weeklySummary: "Resumen Semanal de Salud"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
